// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Ts4gXr_KJ7cJnZ54mVb3HWsixeyhaIA',
    appId: '1:473831757405:web:996242dfb7903db7e29fb4',
    messagingSenderId: '473831757405',
    projectId: 'shimur',
    authDomain: 'shimur.firebaseapp.com',
    storageBucket: 'shimur.firebasestorage.app',
    measurementId: 'G-KGC9NVP62N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBS6yc7OJWk008o3Hv8r7iVxDCDEYdDZ8',
    appId: '1:473831757405:android:ab161f1728b2894be29fb4',
    messagingSenderId: '473831757405',
    projectId: 'shimur',
    storageBucket: 'shimur.firebasestorage.app',
  );
}
